// SPDX-FileCopyrightText: 2026 Atanas G. Rusev
// SPDX-License-Identifier: AGPL-3.0-or-later
import type { AppConfig } from "../types.js";

export function privacySections(config: Pick<AppConfig, "backups" | "privacy">): Array<{ heading: string; body: string }> {
  const backup = config.backups;
  return [
    { heading: "Operator And Privacy Contact", body: config.privacy?.operatorName && config.privacy?.contactEmail
      ? `This instance is operated by ${config.privacy.operatorName}. For private privacy requests, contact ${config.privacy.contactEmail}. Do not post personal data, credentials or privacy requests in public issue trackers.`
      : "The operator has not configured a public privacy contact for this instance. Contact your service administrator privately before submitting personal data. Do not post privacy requests or credentials in public issue trackers." },
    { heading: "Data And Purposes", body: "We process account email, display name, password hashes, memberships, votes, comments, history, invitations, preferences, authentication records and operational timestamps to provide the service. Hosting and security systems may also process IP addresses and request logs. Service delivery uses data necessary to provide the requested service; proportionate security and reliability processing serves legitimate interests. Legal obligations may require additional retention. Do not enter sensitive or confidential production information." },
    { heading: "First-Party Usage Statistics", body: "To understand adoption and voting usage, this instance records per-person/team/day activity timestamps for board entry and successful team actions, and completed-round counts with issue identifiers, participant totals and voter identifiers. Heartbeats and reading statistics do not count as activity. Statistics are retained for 31 days; cleanup runs each minute while the app is running and on startup. Account deletion removes statistics activity and voter identifiers. Workspace purge removes its statistics; aggregate round counts in other retained teams remain until expiry. Team admins see aggregate statistics only for their teams; the super-admin sees installation-wide aggregates. Exports include team/workspace names and totals, not individual account lists or vote content. Backups and downloaded exports follow the separate retention policy. No third-party tracking service is used." },
    { heading: "Access And Providers", body: "We do not sell personal data or use workspace content for advertising or profiling. We do not routinely inspect workspace content; operator access is limited to necessary support, maintenance, security or legal obligations. Other authorized participants see shared workspace content. Hosting and email providers process data needed to deliver the service; enabled integrations such as Jira exchange data as configured by the operator. This is not a promise that data never leaves the server." },
    { heading: "Provider Locations And Transfers", body: config.privacy?.providerDetails || "The operator must publish the hosting/email providers, processing locations and applicable international-transfer safeguards for this instance. These deployment details have not yet been configured." },
    { heading: "Cookies And Browser Storage", body: "Authentication uses a session cookie and a browser-stored session token. Browser storage also remembers interface preferences and the selected team. The app does not include advertising trackers or third-party analytics. Necessary authentication storage supports the requested service; any operator-added non-essential tracking requires its own disclosure and consent assessment." },
    { heading: "Live Data And Account Deletion", body: "Live account and workspace data remain while the service provides the account/workspace; there is no automatic inactivity-deletion deadline. Deleting an owner account purges its owned trial workspaces, teams, voting history and comments from the live database. Other users keep their own accounts and unrelated workspaces. Deletion removes the original account email, credentials, sessions and memberships, but shared history elsewhere retains the former display name with (Deactivated) added. That attribution is still personal data, not anonymisation. Operational records and content referring to a person may also remain; further erasure requests require review." },
    { heading: "Backup Retention", body: backup?.enabled
      ? `App-managed database backups are scheduled every ${backup.intervalHours} hours; at most 3 completed copies are retained, expiring after ${backup.maxAgeDays} days. With the standard configuration this is once per week and three weeks of maximum age. Expiry is checked every minute while the app runs with backups enabled and again on startup; shutdowns, disabled backups or storage failures can delay deletion. The first or overdue snapshot is taken on startup. These copies contain database data, including authentication records, and are restricted to operators. Separate deployment archives and downloaded exports are not managed by this schedule and require operator-controlled deletion. Restores must reapply intervening privacy deletions before reopening access.`
      : "App-managed scheduled backups are disabled on this instance. Existing snapshots are not cleaned while disabled. Separate deployment archives and downloaded exports may exist and require operator-controlled retention and deletion. The optional default schedule is weekly, retaining at most 3 completed database copies with a maximum age of 21 days while the feature is running. Restores must reapply intervening privacy deletions before reopening access." },
    { heading: "Your Privacy Requests", body: "Contact the operator privately to request access or a copy, correction, erasure, restriction or objection, and portability where applicable. The operator may verify identity proportionately and protect other participants’ data. Requests are handled manually; applicable deadlines, normally one month under GDPR, apply. Retention exceptions must be explained, not assumed from this notice. You may complain to your competent data-protection authority; applicable US state rights and appeal routes depend on jurisdiction. No paid certification or blanket GDPR/US-law compliance claim is made." }
  ];
}
